from .base import (
    ID,
    String,
    Boolean,
    DateTime,
    UnsignedInt64,
    Int,
    Float,
    URL,
)
from .objects import (
    object,
    input_object,
    Order,
    LineItem,
    Product,
    ProductVariant,
    PageInfo,
    FulfillmentOrderLineItem,
    ShippingLine,
    Fulfillment,
    Publication,
    ResourcePublication,
)
from .connections import (
    OrderConnection,
    LineItemConnection,
    FulfillmentOrderConnection,
    ProductVariantConnection,
    ResourcePublicationConnection,
)
from .edges import OrderEdge, LineItemEdge, FulfillmentOrderEdge, ProductVariantEdge, ResourcePublicationEdge
from .input_objects import (
    OrderIdentifierInput,
    FulfillmentV2Input,
    ProductPublicationInput,
    ProductUnpublishInput,
    ProductInput,
    OrderInput,
    FulfillmentTrackingInput,
    FulfillmentOrderLineItemsInput,
    FulfillmentOrderLineItemInput
)
from .enums import (
    OrderReturnStatus,
    OrderDisplayFulfillmentStatus,
    OrderDisplayFinancialStatus,
    OrderSortKeys,
    OrderCancelReason,
    ProductVariantInventoryPolicy,
    ProductVariantSortKeys,
    ProductStatus,
)
from .registry import type_registry

# Resolve forward references for interdependent Pydantic models using the shared registry.
type_registry.rebuild_all()
# Convenience alias for legacy callers expecting a namespace dict.
TYPES_NAMESPACE = type_registry.types

__all__ = [
    "ID",
    "String",
    "Boolean",
    "DateTime",
    "UnsignedInt64",
    "Int",
    "Float",
    "URL",
    "input_object",
    "object",
    "LineItem",
    "PageInfo",
    "Order",
    "Product",
    "ProductVariant",
    "Publication",
    "ResourcePublication",
    "OrderIdentifierInput",
    "OrderReturnStatus",
    "OrderDisplayFulfillmentStatus",
    "OrderDisplayFinancialStatus",
    "OrderSortKeys",
    "OrderCancelReason",
    "ProductVariantInventoryPolicy",
    "ProductVariantSortKeys",
    "ProductStatus",
    "LineItemConnection",
    "OrderConnection",
    "FulfillmentOrderConnection",
    "ProductVariantConnection",
    "ResourcePublicationConnection",
    "LineItemEdge",
    "OrderEdge",
    "FulfillmentOrderEdge",
    "ProductVariantEdge",
    "ResourcePublicationEdge",
    "type_registry",
    "TYPES_NAMESPACE",
    "FulfillmentV2Input",
    "ProductPublicationInput",
    "ProductUnpublishInput",
    "ProductInput",
    "OrderInput",
    "FulfillmentTrackingInput",
    "FulfillmentOrderLineItemsInput",
    "FulfillmentOrderLineItem",
    "FulfillmentOrderLineItemInput",
    "ShippingLine",
    "Fulfillment",
]
