from .base import enum

class OrderReturnStatus(enum):
    IN_PROGRESS = "IN_PROGRESS"
    INSPECTION_COMPLETE = "INSPECTION_COMPLETE"
    NO_RETURN = "NO_RETURN"
    RETURN_FAILED = "RETURN_FAILED"
    RETURN_REQUESTED = "RETURN_REQUESTED"
    RETURNED = "RETURNED"

class OrderDisplayFulfillmentStatus(enum):
    FULFILLED = "FULFILLED"
    IN_PROGRESS = "IN_PROGRESS"
    ON_HOLD = "ON_HOLD"
    OPEN = "OPEN"
    PARTIALLY_FULFILLED = "PARTIALLY_FULFILLED"
    PENDING_FULFILLMENT = "PENDING_FULFILLMENT"
    RESTOCKED = "RESTOCKED"
    SCHEDULED = "SCHEDULED"
    UNFULFILLED = "UNFULFILLED"

class OrderDisplayFinancialStatus(enum):
    AUTHORIZED = "AUTHORIZED"
    PAID = "PAID"
    PARTIALLY_PAID = "PARTIALLY_PAID"
    PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED"
    PENDING = "PENDING"
    REFUNDED = "REFUNDED"
    VOIDED = "VOIDED"

class FulfillmentOrderStatus(enum):
    CANCELLED = "CANCELLED"
    CLOSED = "CLOSED"
    IN_PROGRESS = "IN_PROGRESS"
    INCOMPLETE = "INCOMPLETE"
    ON_HOLD = "ON_HOLD"
    OPEN = "OPEN"
    SCHEDULED = "SCHEDULED"

class ProductVariantInventoryPolicy(enum):
    CONTINUE = "CONTINUE"
    DENY = "DENY"

class OrderSortKeys(enum):
    CREATED_AT = "CREATED_AT"
    ID = "ID"
    PROCESSED_AT = "PROCESSED_AT"
    TOTAL_PRICE = "TOTAL_PRICE"
    UPDATED_AT = "UPDATED_AT"
