from .base import enum


class OrderReturnStatus(enum):
    IN_PROGRESS = "IN_PROGRESS"
    INSPECTION_COMPLETE = "INSPECTION_COMPLETE"
    NO_RETURN = "NO_RETURN"
    RETURN_FAILED = "RETURN_FAILED"
    RETURN_REQUESTED = "RETURN_REQUESTED"
    RETURNED = "RETURNED"


class OrderDisplayFulfillmentStatus(enum):
    FULFILLED = "FULFILLED"
    IN_PROGRESS = "IN_PROGRESS"
    ON_HOLD = "ON_HOLD"
    OPEN = "OPEN"
    PARTIALLY_FULFILLED = "PARTIALLY_FULFILLED"
    PENDING_FULFILLMENT = "PENDING_FULFILLMENT"
    RESTOCKED = "RESTOCKED"
    SCHEDULED = "SCHEDULED"
    UNFULFILLED = "UNFULFILLED"


class OrderDisplayFinancialStatus(enum):
    AUTHORIZED = "AUTHORIZED"
    PAID = "PAID"
    PARTIALLY_PAID = "PARTIALLY_PAID"
    PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED"
    PENDING = "PENDING"
    REFUNDED = "REFUNDED"
    VOIDED = "VOIDED"


class FulfillmentOrderStatus(enum):
    CANCELLED = "CANCELLED"
    CLOSED = "CLOSED"
    IN_PROGRESS = "IN_PROGRESS"
    INCOMPLETE = "INCOMPLETE"
    ON_HOLD = "ON_HOLD"
    OPEN = "OPEN"
    SCHEDULED = "SCHEDULED"


class ProductVariantInventoryPolicy(enum):
    CONTINUE = "CONTINUE"
    DENY = "DENY"


class OrderSortKeys(enum):
    CREATED_AT = "CREATED_AT"
    ID = "ID"
    PROCESSED_AT = "PROCESSED_AT"
    TOTAL_PRICE = "TOTAL_PRICE"
    UPDATED_AT = "UPDATED_AT"


class WeightUnit(enum):
    GRAMS = "GRAMS"
    KILOGRAMS = "KILOGRAMS"
    OUNCES = "OUNCES"
    POUNDS = "POUNDS"


class OrderCancelReason(enum):
    CUSTOMER = "CUSTOMER"
    DECLINED = "DECLINED"
    FRAUD = "FRAUD"
    INVENTORY = "INVENTORY"
    OTHER = "OTHER"


class ProductVariantSortKeys(enum):
    ID = "ID"
    NAME = "NAME"
    POSITION = "POSITION"
    RELEVANCE = "RELEVANCE"
    SKU = "SKU"
    INVENTORY_TOTAL = "INVENTORY_TOTAL"


class ProductSortKeys(enum):
    ID = "ID"
    TITLE = "TITLE"
    CREATED_AT = "CREATED_AT"
    UPDATED_AT = "UPDATED_AT"
    RELEVANCE = "RELEVANCE"


class ProductStatus(enum):
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"
    DRAFT = "DRAFT"


class CombinedListingsRole(enum):
    NONE = "NONE"
    PRIMARY = "PRIMARY"
    SECONDARY = "SECONDARY"


class ProductBundleComponentOptionSelectionStatus(enum):
    DESELECTED = "DESELECTED"
    NEW = "NEW"
    SELECTED = "SELECTED"
    UNAVAILABLE = "UNAVAILABLE"


class CountryCode(enum):
    US = "US"
    CA = "CA"
    GB = "GB"
    AU = "AU"
    FR = "FR"
    DE = "DE"
    IT = "IT"
    ES = "ES"
    NL = "NL"
    JP = "JP"
    CN = "CN"
    IN = "IN"
    BR = "BR"
    MX = "MX"


class LocationSortKeys(enum):
    NAME = "NAME"
    ID = "ID"
    CREATED_AT = "CREATED_AT"


class ProductSetUserErrorCode(enum):
    CANNOT_COMBINE_LINKED_AND_NONLINKED_OPTION_VALUES = (
        "CANNOT_COMBINE_LINKED_AND_NONLINKED_OPTION_VALUES"
    )
    CAPABILITY_VIOLATION = "CAPABILITY_VIOLATION"
    DUPLICATE_LINKED_OPTION = "DUPLICATE_LINKED_OPTION"
    DUPLICATED_METAFIELD_VALUE = "DUPLICATED_METAFIELD_VALUE"
    DUPLICATED_OPTION_NAME = "DUPLICATED_OPTION_NAME"
    DUPLICATED_OPTION_VALUE = "DUPLICATED_OPTION_VALUE"
    DUPLICATED_VALUE = "DUPLICATED_VALUE"
    GENERIC_ERROR = "GENERIC_ERROR"
    GIFT_CARD_ATTRIBUTE_CANNOT_BE_CHANGED = "GIFT_CARD_ATTRIBUTE_CANNOT_BE_CHANGED"
    GIFT_CARDS_NOT_ACTIVATED = "GIFT_CARDS_NOT_ACTIVATED"
    HANDLE_NOT_UNIQUE = "HANDLE_NOT_UNIQUE"
    ID_NOT_ALLOWED = "ID_NOT_ALLOWED"
    INPUT_MISMATCH = "INPUT_MISMATCH"
    INVALID_INPUT = "INVALID_INPUT"
    INVALID_METAFIELD = "INVALID_METAFIELD"
    INVALID_METAFIELD_VALUE_FOR_LINKED_OPTION = (
        "INVALID_METAFIELD_VALUE_FOR_LINKED_OPTION"
    )
    INVALID_PRODUCT = "INVALID_PRODUCT"
    INVALID_VARIANT = "INVALID_VARIANT"
    INVENTORY_QUANTITIES_LIMIT_EXCEEDED = "INVENTORY_QUANTITIES_LIMIT_EXCEEDED"
    JOB_ERROR = "JOB_ERROR"
    LINKED_METAFIELD_DEFINITION_NOT_FOUND = "LINKED_METAFIELD_DEFINITION_NOT_FOUND"
    LINKED_OPTIONS_NOT_SUPPORTED_FOR_SHOP = "LINKED_OPTIONS_NOT_SUPPORTED_FOR_SHOP"
    METAFIELD_MISMATCH = "METAFIELD_MISMATCH"
    MISSING_FIELD_REQUIRED = "MISSING_FIELD_REQUIRED"
    NOT_FOUND = "NOT_FOUND"
    OPTION_DOES_NOT_EXIST = "OPTION_DOES_NOT_EXIST"
    OPTION_VALUE_DOES_NOT_EXIST = "OPTION_VALUE_DOES_NOT_EXIST"
    OPTION_VALUES_MISSING = "OPTION_VALUES_MISSING"
    OPTION_VALUES_OVER_LIMIT = "OPTION_VALUES_OVER_LIMIT"
    OPTIONS_OVER_LIMIT = "OPTIONS_OVER_LIMIT"
    PRODUCT_DOES_NOT_EXIST = "PRODUCT_DOES_NOT_EXIST"
    PRODUCT_OPTIONS_INPUT_MISSING = "PRODUCT_OPTIONS_INPUT_MISSING"
    PRODUCT_SUSPENDED = "PRODUCT_SUSPENDED"
    PRODUCT_VARIANT_DOES_NOT_EXIST = "PRODUCT_VARIANT_DOES_NOT_EXIST"
    VARIANTS_INPUT_MISSING = "VARIANTS_INPUT_MISSING"
    VARIANTS_OVER_LIMIT = "VARIANTS_OVER_LIMIT"


class BulkOperationUserErrorCode(enum):
    INVALID = "INVALID"
    LIMIT_REACHED = "LIMIT_REACHED"
    OPERATION_IN_PROGRESS = "OPERATION_IN_PROGRESS"


class BulkOperationStatus(enum):
    CANCELED = "CANCELED"
    CANCELING = "CANCELING"
    COMPLETED = "COMPLETED"
    CREATED = "CREATED"
    EXPIRED = "EXPIRED"
    FAILED = "FAILED"
    RUNNING = "RUNNING"


class BulkOperationType(enum):
    MUTATION = "MUTATION"
    QUERY = "QUERY"
