from .base import enum

class OrderReturnStatus(enum):
    IN_PROGRESS = "IN_PROGRESS"
    INSPECTION_COMPLETE = "INSPECTION_COMPLETE"
    NO_RETURN = "NO_RETURN"
    RETURN_FAILED = "RETURN_FAILED"
    RETURN_REQUESTED = "RETURN_REQUESTED"
    RETURNED = "RETURNED"