name: Ruff

on: [pull_request]

jobs:
  ruff:
    runs-on: [self-hosted, windows, X64]
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/ruff-action@v1
        with:
          args: check .